# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
# TODO

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
# TODO

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

[92 77 63 42 13 74 79 85 97 59]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

I copied the above comma separated numbers with missing values into a file called "file.txt".

In [89]:
# https://numpy.org/devdocs/user/how-to-io.html
with open("file.txt", "r") as f:
    print(f.read())

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11


The docs are on point for this one, providing a lot of options:

In [90]:
# masked array output
np.genfromtxt("file.txt", delimiter=",", usemask=True)

masked_array(
  data=[[1.0, 2.0, 3.0, 4.0, 5.0],
        [6.0, --, --, 7.0, 8.0],
        [--, --, 9.0, 10.0, 11.0]],
  mask=[[False, False, False, False, False],
        [False,  True,  True, False, False],
        [ True,  True, False, False, False]],
  fill_value=1e+20)

In [91]:
# array output
np.genfromtxt("file.txt", delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [92]:
# array output, fill in specified value for missing data
np.genfromtxt("file.txt", delimiter=",", dtype=np.int8, filling_values=99)

array([[ 1,  2,  3,  4,  5],
       [ 6, 99, 99,  7,  8],
       [99, 99,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [93]:
# https://www.scaler.com/topics/what-is-the-equivalent-of-enum-in-numpy/
arr=np.arange(2,25,3)
print("Array arr: ",arr)
for index,item in np.ndenumerate(arr):
  print("index:",index,"item:",item)

Array arr:  [ 2  5  8 11 14 17 20 23]
index: (0,) item: 2
index: (1,) item: 5
index: (2,) item: 8
index: (3,) item: 11
index: (4,) item: 14
index: (5,) item: 17
index: (6,) item: 20
index: (7,) item: 23


In [97]:
import numpy as np
arr=np.arange(1,25,2)
arr1=arr.reshape(3,4)
print("Array arr:\n",arr1)
print()
print("Elements of the array with their indices:")
for index,item in np.ndenumerate(arr1):
  print("index:",index,"item:",item)


Array arr:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]

Elements of the array with their indices:
index: (0, 0) item: 1
index: (0, 1) item: 3
index: (0, 2) item: 5
index: (0, 3) item: 7
index: (1, 0) item: 9
index: (1, 1) item: 11
index: (1, 2) item: 13
index: (1, 3) item: 15
index: (2, 0) item: 17
index: (2, 1) item: 19
index: (2, 2) item: 21
index: (2, 3) item: 23


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

We want to simulate the following equation:
$$
f(x)=\frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2}
$$

In [99]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-79.php

First we generate the input points:

In [10]:
x = np.linspace(-1,1,10)
sigma, mu = 1.0, 0.0 # define mean and standard deviation

Then we model the equation shown:

In [11]:
g = np.exp(-( (x-mu)**2 / ( 2.0 * sigma**2 ) ) )

In [12]:
g

array([0.60653066, 0.7389913 , 0.85699689, 0.94595947, 0.99384617,
       0.99384617, 0.94595947, 0.85699689, 0.7389913 , 0.60653066])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
# TODO

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [17]:
matrix = np.random.random((5,5))
matrix

array([[0.7051552 , 0.82737482, 0.37961503, 0.53487244, 0.14508759],
       [0.72343635, 0.69499332, 0.07633495, 0.54305375, 0.36648168],
       [0.61237728, 0.67455657, 0.30922683, 0.52292898, 0.16472013],
       [0.58409415, 0.19392864, 0.54450576, 0.43401131, 0.81413625],
       [0.33025539, 0.50547489, 0.88544298, 0.83784478, 0.9529496 ]])

The mean of the first row:

In [20]:
matrix[0,:].mean()

0.518421015566759

In [24]:
row_means = matrix.mean(axis=1)
row_means

array([0.51842102, 0.48086001, 0.45676196, 0.51413522, 0.70239353])

In [25]:
row_means.shape

(5,)

In [27]:
row_means = row_means.reshape(5,1)
row_means

array([[0.51842102],
       [0.48086001],
       [0.45676196],
       [0.51413522],
       [0.70239353]])

In [28]:
matrix = matrix - row_means
matrix

array([[ 0.18673418,  0.30895381, -0.13880598,  0.01645142, -0.37333343],
       [ 0.24257634,  0.21413331, -0.40452505,  0.06219374, -0.11437833],
       [ 0.15561532,  0.21779461, -0.14753513,  0.06616702, -0.29204183],
       [ 0.06995893, -0.32020658,  0.03037054, -0.08012391,  0.30000103],
       [-0.37213813, -0.19691864,  0.18304945,  0.13545125,  0.25055607]])

Rougier gives a better solution:

In [29]:
# Author: Warren Weckesser
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

In [30]:
# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

#### 59. How to sort an array by the nth column? (★★☆)

In [31]:
# https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-9.php
nums = np.random.randint(0,10,(3,3))
print(nums)

[[4 1 3]
 [2 6 4]
 [1 7 8]]


In [33]:
print("\nSort the said array by the nth column: ")
print(nums[nums[:,0].argsort()])


Sort the said array by the nth column: 
[[1 7 8]
 [2 6 4]
 [4 1 3]]


In [34]:
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])


Sort the said array by the nth column: 
[[4 1 3]
 [2 6 4]
 [1 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [35]:
# https://stackoverflow.com/questions/6252280/find-the-most-frequent-number-in-a-numpy-array
a = np.random.randint(0,10, (5,5))
print(a)
values, counts = np.unique(a, return_counts=True)

[[0 5 0 7 1]
 [9 3 7 5 1]
 [5 3 2 1 2]
 [5 9 4 8 7]
 [2 1 2 0 8]]


In [36]:
values

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [37]:
counts

array([3, 4, 4, 2, 1, 4, 3, 2, 2], dtype=int64)

In [38]:
values[counts.argmax()]

1

To list the n most frequent elements:

In [42]:
ind = np.argpartition(-counts, kth=5)[:5]
print(values[ind])  # prints the 5 most frequent elements

[1 2 5 0 7]


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
# ---------------------------------------------------------------------------- #
#                                this is a test                                #
# ---------------------------------------------------------------------------- #

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)